import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Navbar from "../components/Navbar";
import ThemeProvider from "../providers/ThemeProvider";
import Background from "../components/Background";

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <ThemeProvider>
            <Background>
                <Head>
                    <title>vctqs1 Portfolio</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Navbar />
                <Component {...pageProps} />
            </Background>
        </ThemeProvider>
    );
}
export default MyApp;
